### ISSUE TITLE
Cannot read property 'statusCode' of undefined

### ISSUE THREAD

**Issue by kevincennis** [logdna/logdna-agent#148]
As far as I can tell, this error was introduced in [this commit](https://github.com/logdna/logdna-agent/commit/b7bbb3e58eb1bcd5a8f27a7813fe48d35dd65135).

On line 73 of `linebuffer.js`, there's a check to see if `res.statusCode === 207` – but this occurs _before_ checking to see if there was an error.

```
2019-12-09 20:33:05 0000 [error] uncaught error: TypeError: Cannot read property 'statusCode' of undefined
    at Request.posthandler [as _callback] (/usr/bin/lib/linebuffer.js:73:17)
    at self.callback (/usr/bin/node_modules/request/request.js:185:22)
    at Request.emit (events.js:210:5)
    at Request.onRequestError (/usr/bin/node_modules/request/request.js:881:8)
    at ClientRequest.emit (events.js:210:5)
    at TLSSocket.socketErrorListener (_http_client.js:406:9)
    at TLSSocket.emit (events.js:210:5)
    at emitErrorNT (internal/streams/destroy.js:92:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
```

**Comment by smusali** [comment]
Hi @kevincennis, 

Thanks for reporting this!

It should be fixed now - can you `purge` and reinstall the agent with the same instructions?

Please, let us know how it goes.

**Comment by kevincennis** [comment]
All set. Thanks!
