### ISSUE TITLE
Illegal operation on a directory, read

### ISSUE THREAD

**Issue by stevepeak** [logdna/logdna-agent#20]
Starting new pod results in:

```rb
2017-04-26T13:51:07.122756255Z [170426 13:51:07] ------------------------------------------------------------------
2017-04-26T13:51:07.125148525Z [170426 13:51:07] Uncaught Error: Error: EISDIR: illegal operation on a directory, read
2017-04-26T13:51:07.125162186Z at Error (native)
2017-04-26T13:51:07.125165815Z at Object.fs.readSync (fs.js:651:19)
2017-04-26T13:51:07.125168470Z at Object.fs.readFileSync (fs.js:472:24)
2017-04-26T13:51:07.125171177Z at nexe.js:164:98
2017-04-26T13:51:07.125178046Z at tryCatcher (nexe.js:12813:23)
2017-04-26T13:51:07.125181216Z at Promise._settlePromiseFromHandler (nexe.js:10850:31)
2017-04-26T13:51:07.125183787Z at Promise._settlePromise (nexe.js:10907:18)
2017-04-26T13:51:07.125186292Z at Promise._settlePromise0 (nexe.js:10952:10)
2017-04-26T13:51:07.125188847Z at Promise._settlePromises (nexe.js:11031:18)
2017-04-26T13:51:07.125191382Z at Promise._fulfill (nexe.js:10976:18)
2017-04-26T13:51:07.125194199Z at Promise._resolveCallback (nexe.js:10771:57)
2017-04-26T13:51:07.125196679Z at Promise._settlePromiseFromHandler (nexe.js:10862:17)
2017-04-26T13:51:07.125199187Z at Promise._settlePromise (nexe.js:10907:18)
2017-04-26T13:51:07.125210652Z at Promise._settlePromise0 (nexe.js:10952:10)
2017-04-26T13:51:07.125213520Z at Promise._settlePromises (nexe.js:11027:18)
2017-04-26T13:51:07.125215983Z at Async._drainQueue (nexe.js:7923:16)
2017-04-26T13:51:07.126816694Z [170426 13:51:07] ------------------------------------------------------------------
```

> Provider: GCP via Container Engine.

Thank you!

**Comment by leeliu** [comment]
Hi Steve, sorry for the delay in response. Was there any log lines before this error? Can you also share if you've had the agent monitor other file paths other than the /var/log default?

**Comment by stevepeak** [comment]
Hey @leeliu no worries 😄 

> Was there any log lines before this error?

No, this is the only log data provided.


> Can you also share if you've had the agent monitor other file paths other than the /var/log default?

I set this up with no configuration on GCP+Kubernetes. I suspect the issue was concerning disk read/write, but not sure. I can try to replicate when I get back into my infrastructure objectives.

**Comment by quickguard** [comment]
same issue on GKE

**Comment by leeliu** [comment]
Thanks. I'm in the process of trying to repo this on GKE. I might've asked one of you to provide this but it'll help overall in my troubleshooting. I'm not sure if there's a way to do a `ls -l /var/log` on the node itself but the output of that would be useful. EISDIR basically means we're trying to tail a file but it turns out to be a folder instead (very strange), so it'd be nice to figure out at least which one is responsible.

**Comment by stevepeak** [comment]
@leeliu The node I setup was out-of-the-box. I do not recall doing any special setup beyond the default.

**Comment by leeliu** [comment]
Alright...we managed to duplicate this on GKE. This new update fixes it. You just need to re-run ```kubectl create -f https://raw.githubusercontent.com/logdna/logdna-agent/master/logdna-agent-ds.yaml``` and it should now work in GKE. And we verified this on our GCP account.

If you care about what caused it, keep reading, otherwise, you should be good to go. Basically in order for us to get the actual hostname of the box, we'd mount /etc/hostname on the host to /etc/logdna-hostname inside the container. But for some reason /etc/hostname either doesn't exist or exists as a directory on the host...very strange. Anyway the fix basically checks that it's a file before attempting to read it.
